# Minimum players to start the Hunger Games
min-players: 2
# Number of supply drop chest to spawn
chest-spawn-num: 3
durations:
  # Lobby phase duration in seconds where players can login and choose their class
  lobby: 30
  # Safe area duration in seconds where players can destroy blocks and collect items but cannot hit other players
  safe-area: 30
  # Winner celebrations duration in seconds
  winner-celebrations: 15
  # Fireworks celebrations duration in seconds
  fireworks: 15 
  # How many seconds after the start of the game (after safe-area phase) is the supply chest dropped
  first-supply-drop: 30
  # Interval seconds between every supply chest drop
  supply-drop: 60
  # How many minutes a player can be stationary during the playing phase before getting kicked
  idle-timeout: 2
world-border:
  # Max world size dimension in blocks
  max-size: 128
  # Min world size dimension in blocks
  min-size: 2
  # Enable the world collapse feature
  collapse: true
  # How many seconds to reduce world border by collapse-radius value
  collapse-counter-seconds: 60
  # World border collapse radius
  collapse-radius: 20
server:
  id: 1
  # When server is started, automatically start a new Hunger Games session
  auto-start: false
  # Automatically restart server when Hunger Games session is finished
  auto-restart: false
database:
  # Enable and connect to a database to save Hunger Games informations and statistics
  enable: false
  # Connection string for the database
  connection-string: jdbc:mysql://51.38.125.46:3306/hunger_games
  # Database Connection user credentials
  user: test
  password: test