name: ${name}
version: ${version}
description: ${description}
api-version: ${apiVersion}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    test:
        description: An example command
        permission: perm.op
        usage: /<command>
    restart-hg-server:
        description: An example command
        permission: perm.op
        usage: /<command>
    current-phase:
        description: An example command
        permission: perm.op
        usage: /<command>
    start-hg:
        description: An example command
        permission: perm.op
        usage: /<command>
    bowman:
        description: Shot other players with a bow and some arrows
        permission: perm.general
        usage: /<command>
    armored:
        description: Cover yourself with a full iron armor set
        permission: perm.general
        usage: /<command>
    doglover:
        description: Tame the nature and kill other players with your dog
        permission: perm.general
        usage: /<command>
    lavaman:
        description: Burn BURN BURN!!!
        permission: perm.general
        usage: /<command>
permissions:
   perm.general:
      default: true
   perm.op:
      default: op