name: ${name}
version: ${version}
description: ${description}
api-version: ${apiVersion}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    test:
        description: An example command
        permission: spigotplugin.test
        usage: /<command>
    restart-hg-server:
        description: An example command
        permission: spigotplugin.restart-hg-server
        usage: /<command>
    current-phase:
        description: An example command
        permission: spigotplugin.current-phase
        usage: /<command>
    start-hg:
        description: An example command
        permission: spigotplugin.start
        usage: /<command>
    bowman:
        description: An example command
        permission: perm.general
        usage: /<command>
    armored:
        description: An example command
        permission: perm.general
        usage: /<command>
    doglover:
        description: An example command
        permission: perm.general
        usage: /<command>
permissions:
   perm.general:
      default: true
   perm.op:
      default: op