name: ${name}
version: ${version}
description: ${description}
api-version: ${apiVersion}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    test:
        description: An example command
        permission: perm.op
        usage: /<command>
    restart-hg-server:
        description: An example command
        permission: perm.op
        usage: /<command>
    current-phase:
        description: An example command
        permission: perm.op
        usage: /<command>
    messages:
        description: An example command
        permission: perm.op
        usage: /<command>
    start-hg:
        description: An example command
        permission: perm.op
        usage: /<command>
    scoreboard:
        description: Show players that won the most match
        permission: perm.general
        usage:
          /<command> Show current game players that won the most match
          /<command> global Show global players that won the most match
    class:
        description: Use the command to select your class
        permission: perm.general
        usage:
          /<command> bowman Shot other players with a bow and some arrows
          /<command> armored Cover yourself with a full iron armor set
          /<command> doglover Tame the nature and kill other players with your dog
          /<command> lavaman Burn BURN BURN!!!
          /<command> miner Dig in, my friend!
          /<command> mole Dig out, my friend!
          /<command> ghost Let's get invisible
          /<command> teleporter I'm here... not anymore
          /<command> barbarian WWOOWOWOW
          /<command> hardcore Are you crazy!?!?
permissions:
   perm.general:
      default: true
   perm.op:
      default: op